name: terraform Lint
description: GitHub Action that lints a Terraform based repository via [action-pre-commit](https://github.com/open-turo/action-pre-commit)
inputs:
  checkout-repo:
    required: false
    description: Perform checkout as first step of action
    default: "true"
  github-token:
    required: true
    description: GitHub token that can checkout the consumer repository. e.g. 'secrets.GITHUB_TOKEN'
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      if: inputs.checkout-repo == 'true'
      with:
        # Use fetch-depth of zero to obtain all commit history so that commit message linting can
        # be properly performed.
        fetch-depth: 0
    - name: Setup tools
      # Provide opportunity to install terraform, golang, and others
      uses: open-turo/action-setup-tools@v2
    - name: Authorize
      uses: open-turo/action-git-auth@v3
      with:
        github-personal-access-token: ${{ inputs.github-token }}
    - name: Pre-commit
      uses: open-turo/action-pre-commit@v3
    - name: Check release notes on pull_request
      if: github.event_name == 'pull_request'
      uses: open-turo/actions-release/lint-release-notes@v5
