name: "golang Lint"
description: "Lints golang repository"
inputs:
  checkout-repo:
    required: false
    description: "Perform checkout as first step of action"
    default: "true"
  github-token:
    required: true
    description: "GitHub token that can checkout the repository. e.g. 'secrets.GITHUB_TOKEN'"
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      if: inputs.checkout-repo
      with:
        fetch-depth: 0
    - name: Setup tools
      uses: open-turo/action-setup-tools@v1
      ## Installs version of golang found in .go-version
    - name: Authorize
      uses: open-turo/action-git-auth@v1
      with:
        token: ${{ inputs.github-token }}
    - name: Commitlint
      uses: wagoid/commitlint-github-action@v4
      with:
        configFile: .commitlintrc.yaml
    - name: Run npm ci if needed
      if: hashFiles('package-lock.json') != ''
      shell: bash
      run: npm ci
    - name: Pre-commit
      uses: open-turo/action-pre-commit@v1
