name: "Go Release & Publish"
description: "Publish a new release of the project"
inputs:
  github-token:
    description: "Github token to use for authentication"
    required: true
  go-version:
    description: "Go version to use for building"
    required: true
    default: 1.17.3
outputs:
  version:
    description: "Version of the project"
    value: ${{ steps.release.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Initial step
      shell: bash
      run: pwd
    - name: Authorize
      uses: open-turo/action-git-auth@v1
      with:
        token: ${{ inputs.github-token }}
    - uses: go-semantic-release/action@v1
      id: release
      with:
        github-token: ${{ inputs.github-token }}
    - name: Prior to fetch tags
      shell: bash
      run: pwd
    - name: Fetch tags
      shell: bash
      run: |
        git fetch --tags
        git clean -fd
    - uses: goreleaser/goreleaser-action@v2
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GOPRIVATE: github.com/turo/
        GOVERSION: ${{ inputs.go-version }}
      with:
        args: release
